fix(embed): fix multiple embeds (#1078)
docsifyjs/docsify pull request #1324
Opened 2020-08-01 23:09 UTC by madhavarshney

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

2020-08-01 23:29 UTC, madhavarshney commented on src/core/render/embed.js
> +      done(cloned);
IMO all this cloning here is a bit odd...

2020-08-03 02:58 UTC, madhavarshney commented
I'm currently a bit busy, so if anyone would like to add some tests, then go ahead! Otherwise, I'll try to do it soon (hopefully near the end of this week).

2020-08-09 19:29 UTC, anikethsaha commented
Thanks for the PR. 

@madhavarshney take your time , no hurry at all. You can also convert this to draft if its ok by you in order to let others know that this is still WIP

2020-09-01 14:22 UTC, anikethsaha approved these changes
Need tests for this rest its ok.

2020-09-23 09:26 UTC, Koooooo-7 approved these changes

2020-09-23 10:38 UTC, sy-records requested changes
Waiting to add a test

2021-07-17 20:22 UTC, madhavarshney commented
This has been fixed with the upgrade to `marked.js`.

2021-07-17 20:22 UTC, closed without merging