fix: Cannot read property level of undefined
docsifyjs/docsify pull request #1357
Opened 2020-08-26 00:47 UTC by sy-records

**Summary**

fix #1356

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

2020-08-26 05:44 UTC, anikethsaha requested changes
Optional Suggestion : Can we have some tests

2020-08-26 16:13 UTC, Koooooo-7 reviewed
could you give more details about this change?

and I m thinking about what kind of exceptions that we need fixed/covered and which should let them throw out, for the wrong configurations/ illegal usages.
cuz it seems weird that when user set up some configurations, there is no any exception output, but it dose not work.
Some other front-end projects, when you use wrong `undefind properties`/ configurations, they will throw the exceptions also.

2020-08-26 23:31 UTC, sy-records commented
@Koooooo-7 You can try it yourself, it causes the sidebar to fail to render here.

Run the following README.md:
```
# Heading 1

Test

## Heading 2

### Heading 3A

Lorem ipsum

#### Heading 4A

##### Heading 5A

Lorem ipsum

### Heading 3B

Lorem ipsum

#### Heading 4B <!-- {docsify-ignore} -->

##### Heading 5B

Lorem ipsum
```

2020-08-29 16:56 UTC, Koooooo-7 approved these changes

2020-08-30 05:39 UTC, anikethsaha approved these changes

2020-09-01 09:34 UTC, merged