fix: search titles containing ignored characters
docsifyjs/docsify pull request #1395
Opened 2020-10-13 10:33 UTC by sy-records

**Summary**

If ignore is set, we should remove it from the search title

![image](https://user-images.githubusercontent.com/33931153/95849707-6537d700-0d82-11eb-9181-2c55fd3078f4.png)

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

2020-10-13 11:52 UTC, anikethsaha requested changes
Can you write tests for this if possible ?

2020-10-13 12:25 UTC, Koooooo-7 submitted a review, later dismissed
As @anikethsaha  said, try to write a test, so do I. 😜

2020-10-15 06:35 UTC, sy-records commented
Waiting for the #1398 merge to fix CI

2020-10-15 13:15 UTC, anikethsaha approved these changes

2020-11-08 08:47 UTC, Koooooo-7 approved these changes

2020-11-08 08:48 UTC, merged