fix: title error when sidebar link exists with image
docsifyjs/docsify pull request #1404
Opened 2020-10-20 01:22 UTC by sy-records

**Summary**

fix https://github.com/docsifyjs/docsify/issues/1353#issuecomment-699716563

![image](https://user-images.githubusercontent.com/33931153/96528557-a44fb600-12b5-11eb-8243-8e32549279bc.png)

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

2020-10-20 14:26 UTC, Koooooo-7 submitted a review, later dismissed

2020-10-26 12:13 UTC, Koooooo-7 submitted a review, later dismissed

2020-11-20 21:05 UTC, jhildenbiddle requested changes
Tested and confirmed that the fix is working. Two minor code style change requests.

Nice work! 😄

2020-11-20 21:05 UTC, jhildenbiddle commented on test/unit/render-util.test.js
> +    test('remove span and img', () => {
Another minor nit-pick...

The regular expression used will remove *any* HTML tag, not just `<span>` and `<img>` tags. I think we can remove the nested `describe()` block and rename the `test()` block accordingly:

```js
describe('core/render/tpl', () => {
   test('remove html tags in tree', () => {
```

2020-11-21 15:51 UTC, jhildenbiddle approved these changes
Looks good! Thanks for making the changes. 👍

2020-11-22 14:39 UTC, Koooooo-7 approved these changes

2020-11-22 22:23 UTC, merged