fix: allow also " inside of an embed
docsifyjs/docsify pull request #1598
Opened 2021-06-22 12:35 UTC by luwol03

## **Summary**

I fixed a bug where `":include"` is not handled like `':include'`. This is not working because the type of quotes are not supported. The default prettier configuration changes the `''` to `""`. And if you have auto format toggled on, you're not be able to save the file with the right quotes.

## **What kind of change does this PR introduce?**

I added added the `"` also the the replace regex

```js
str = str
      .replace(/^('|")/, '')
      .replace(/('|")$/, '')
```

## **For any code change,**

- [x] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added (I cant find some tests for that already.)

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Related issue, if any:**

closes #1597 

## **Tested in the following browsers:**

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

2021-06-23 01:27 UTC, sy-records reviewed
Can you add a test for this?

2021-06-23 11:35 UTC, Koooooo-7 commented
@sy-records 
As we all know, this func `getAndRemoveConfig ` has been used for much places.
It seems we need separate it for different functions in case of unpredicted issues.
WDTY?

2021-06-23 11:36 UTC, Koooooo-7 reviewed
@sy-records
As we all know, this func getAndRemoveConfig has been used for much places.
It seems we need separate it for different functions in case of unpredicted issues.
WDTY?

2021-06-24 01:29 UTC, sy-records commented
Yes, you're right.

2021-06-24 23:10 UTC, trusktr commented
> It seems we need separate it for different functions in case of unpredicted issues.

@Koooooo-7 What do you mean?

2021-06-25 01:25 UTC, Koooooo-7 commented
> > It seems we need separate it for different functions in case of unpredicted issues.
> 
> @Koooooo-7 What do you mean?

This func r working in multi place to get configs. such as titles ,  sidebar headings.
If we add " for embed files,  it might cause other problems in other places.
so, we may need separate this func , for sidebar, for titles and for embed files.

2021-06-25 02:52 UTC, trusktr commented
@Koooooo-7 I see what you're saying, although it seems very unlikely. My guess would be that there is no one relying on he non-working double quotes.

It seems multiple people have hit this issue, and we closed the issues. It was in fact working before, then it broke:

- https://github.com/docsifyjs/docsify/issues/1587
- https://github.com/docsifyjs/docsify/issues/1555
- https://github.com/docsifyjs/docsify/issues/1005

2021-06-25 03:18 UTC, Koooooo-7 commented
@trusktr  I checked this func history, it seems never support the `"` before, the docs either.
You could check [this func](https://github.com/docsifyjs/docsify/pull/708/files) since `Dec 5, 2018` and earlier.
If we support it right now, it would remove the `"` in other places also. 
So, I prefer to separate this func only for different places.

2021-06-25 14:40 UTC, luwol03 commented
> Can you add a test for this?

sure, will try that.

> > > It seems we need separate it for different functions in case of unpredicted issues.
> > 
> > 
> > @Koooooo-7 What do you mean?
> 
> This func r working in multi place to get configs. such as titles , sidebar headings.
> If we add " for embed files, it might cause other problems in other places.
> so, we may need separate this func , for sidebar, for titles and for embed files.

I dont think so. I would also like to use the double ones inside of headlines, or other stuff. Everywhere I can use this style.

And another question, do you prefere an clean commit history, so should I rebase merge upstream changes?

2021-06-25 15:19 UTC, Koooooo-7 commented
@luwol03  of cuz we can support this feat for those configs. instead, how about those titles/other stuff without configs but with " ?

2021-06-25 15:31 UTC, luwol03 commented
> @luwol03 of cuz we can support this feat for those configs. instead, how about those titles/other stuff without configs but with " ?
> e.g a title `this is "my title"`.

Then we should improve the function, so that it only replaces the quotes, if they are followed by a `:xxxx` and there is also a closing one.

2021-06-25 15:40 UTC, Koooooo-7 commented
> > @luwol03 of cuz we can support this feat for those configs. instead, how about those titles/other stuff without configs but with " ?
> > e.g a title `this is "my title"`.
> 
> Then we should improve the function, so that it only replaces the quotes, if they are followed by a `:xxxx` and there is also a closing one.

agreed.
If possible, glad to see a good solution for this func/regx to solve those issues above.

2021-06-25 17:04 UTC, Koooooo-7 approved these changes

2021-06-25 17:47 UTC, luwol03 commented
Is this normal, that your e2e tests failed?

2021-06-25 17:50 UTC, Koooooo-7 commented
> Is this normal, that your e2e tests failed?

It seems not this changes broken, it's okay.
I would retry it.

2021-06-25 18:10 UTC, trusktr commented
> If we support it right now, it would remove the `"` in other places also.

@Koooooo-7 can you point them out?

2021-06-25 18:13 UTC, trusktr commented
> Is this normal, that your e2e tests failed?

Sometimes it fails for some reason despite that it shouldn't. Needs a fix.

2021-06-25 19:03 UTC, luwol03 commented
Before merge, I will try that:

> Then we should improve the function, so that it only replaces the quotes, if they are followed by a :xxxx and there is also a closing one.

2021-06-25 19:22 UTC, trusktr commented
> Before merge, I will try that:
> 
> > Then we should improve the function, so that it only replaces the quotes, if they are followed by a :xxxx and there is also a closing one.

Is anyone using it without the `:`?

2021-06-25 19:25 UTC, trusktr commented
Here is an example without the colon: https://github.com/docsifyjs/docsify/issues/1587#issuecomment-854293984

2021-06-25 19:35 UTC, trusktr commented on test/unit/render-util.test.js
> +  });
I wonder what the behavior should actually be. Seems funky that it leaves things behind. Seems like it should handle everything.

2021-06-25 20:17 UTC, trusktr approved these changes

2021-06-25 20:17 UTC, trusktr commented
@jhildenbiddle One test or other keeps randomly failing.

2021-06-25 20:21 UTC, trusktr commented
Investigating the failures. Let's not merge until we know it isn't the change from here. Seems unlikely that it is.

2021-06-25 20:21 UTC, trusktr requested changes
Looks good. I'm not requesting any changes, just blocking from merging to ensure the test is just flaky (that's what it seems like).

2021-06-25 22:34 UTC, trusktr approved these changes

2021-06-25 22:42 UTC, trusktr commented
> improve the function, so that it only replaces the quotes, if they are followed by a :xxxx and there is also a closing one.

I don't think we should do that, it could break this: `"this-is-currently-ignored :but=this-currently-works"`. If we do, it can be a new PR.

Thanks @luwol03! Merging, since tests pass except one at random, which seems unrelated.

2021-06-25 22:42 UTC, merged

2021-06-26 07:17 UTC, luwol03 commented
Oh, A few seconds ago, I pushed my changes, before I relized, that you already merged this changes :joy:

2021-06-27 06:01 UTC, sy-records commented
@luwol03 You can open a new PR

2021-06-28 07:57 UTC, luwol03 commented
> @luwol03 You can open a new PR
@sy-records done - see #1603