Further improvements to Docsify ReadMe.
docsifyjs/docsify pull request #2139
Opened 2023-07-17 21:16 UTC by paulhibbitts

Further improvements to Docsify ReadMe.

## **Summary**

## **What kind of change does this PR introduce?**

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Related issue, if any:**

## **Tested in the following browsers:**

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-07-17 21:45 UTC, trusktr submitted a review, later dismissed

2023-07-17 23:12 UTC, sy-records requested changes

2023-07-17 23:12 UTC, sy-records commented on README.md
> +- Compatible with IE11
It is no longer compatible with IE11.

2023-07-18 01:46 UTC, sy-records approved these changes
LGTM. Thank you!

2023-07-18 03:02 UTC, merged