fix: fix loadSider false render structure issue
docsifyjs/docsify pull request #2470
Opened 2024-07-19 13:32 UTC by Koooooo-7

## Summary

## Related issue, if any:

## What kind of change does this PR introduce?

## For any code change,

- [ ] Related documentation has been updated, if needed
- [ ] Related tests have been added or updated, if needed

## Does this PR introduce a breaking change?

Yes
No

## Tested in the following browsers:

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2024-07-19 18:35 UTC, jhildenbiddle commented
@Koooooo-7 --

Tested this PR today. The nesting appears to be fixed (🥳), however a bug has been introduced where it appears that an attempt is made to load a sidebar file named `null.md` even when `loadSidebar: true`. You can see this by looking at the network tab of your browser's dev tools. The failing e2e test also shows the error message appearing in the console:

```
       "beforeEach",
        "afterEach-async",
        "afterEach",
        "doneEach",
        "ready",
    +   "Failed to load resource: the server responded with a status of 404 (Not Found)",
```

2024-07-20 08:49 UTC, Koooooo-7 commented
> however a bug has been introduced where it appears that an attempt is made to load a sidebar file named `null.md` even when `loadSidebar: true`. 

@jhildenbiddle  ...nice catch. I got a silly mistake to re-load the sidebar twice.
Fixed.

2024-07-25 18:15 UTC, jhildenbiddle requested changes
A few issues I've found:

1. When loading sidebars from a file (`loadSidebar: true`), there are now multiple `.app-sub-sidebar` elements when there should only be one (the `<ul>` that contains the links generated from page headings). I'm guessing this is because the rendering loop is adding the `app-sub-sidebar` class to each `<ul>`element (top-level and each nested list).

   <img src="https://github.com/user-attachments/assets/e91d64ef-737c-472f-8a33-86dd98a7b486" width="300">

2. When generating sidebars without a file (`loadSidebar: false`), there is no `app-sub-sidebar` element. As mentioned above, the `<ul>` element that links generated from page headings should always have the `app-sub-sidebar` class name applied.

   <img src="https://github.com/user-attachments/assets/0eb12e41-7799-4a91-8286-9b11010b50e7">

3. Separate but related, it appears #2467 introduced a new behavior that results in the top-level `<h1>` tag appearing as a nested link. This isn't necessarily *wrong*, but it is a new and unexpected behavior. I mention it here only because it seems related to the work being done here.

   **Docsify v4**
   
   <img src="https://github.com/user-attachments/assets/4bffb4d5-06b8-4448-ba4e-7c2471c14303" width="200">

   **Docsify v5 style overhaul** (#2469 Preview)
   
   <img src="https://github.com/user-attachments/assets/b31873b2-7e25-4196-bdaa-539810a5020f" width="200">
   
   **This PR**

   <img src="https://github.com/user-attachments/assets/3fa9c813-7916-4257-a5e5-f2977d4d7594" width="200">

2024-07-26 05:57 UTC, Koooooo-7 commented on test/integration/sidebar.test.js
> +import { expect } from '@playwright/test';
I use the wrong function import. fix.

2024-07-26 16:15 UTC, Koooooo-7 commented
@jhildenbiddle  ---
Fix the  issue 1 and 3.
The Issue 2, once  we have a final decision I will update asap.

2024-07-27 15:10 UTC, jhildenbiddle approved these changes
LGTM! Thank you, @Koooooo-7!

2024-07-27 19:37 UTC, paulhibbitts approved these changes
Thanks so much @Koooooo-7 , looks good with my testing with Docsify-This as well.

2024-07-28 08:18 UTC, merged