chore(docs): correct mermaid docs after upgrade marked
docsifyjs/docsify pull request #2490
Opened 2024-08-16 13:14 UTC by Koooooo-7

## Summary

correct mermaid docs after upgrade marked, and mentioned its limitation.
We should adoption the mermaid to resolve the async issue in #1433 then.

## Related issue, if any:

## What kind of change does this PR introduce?

Docs
## For any code change,

- [x] Related documentation has been updated, if needed
- [ ] Related tests have been added or updated, if needed

## Does this PR introduce a breaking change?

Yes
No

## Tested in the following browsers:

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2024-08-16 15:35 UTC, paulhibbitts reviewed
Hi @Koooooo-7 , thanks so much for identifying this issue! I've been using the Mermaid plugin (https://github.com/Leward/mermaid-docsify which seems to support v10) so I did not even know of any support of Mermaid was possible in Docsify itself🙂

Happy to help tweak the updated docs, here is a first pass:

```
## Limited Support of mermaid

!> Currently, docsify only supports mermaid version `v9.3.0` (as the async render in mermaid `v10.x` is not yet supported in docsify)
```

I also have a preview build with this change for you to see:
https://paulhibbitts.github.io/docsify-v5-preview/#/markdown?id=limited-support-of-mermaid

And tried an example Mermaid 9.x diagram🙂
https://paulhibbitts.github.io/docsify-v5-preview/#/test-5

2024-08-16 15:52 UTC, trusktr commented on docs/markdown.md
> +!> Currently, docsify doesn't support the async mermaid render ( the limited supported latest merimaid version is `v9.3.0`).
merimaid -> mermaid

Perhaps 

> the latest mermaid version supported is `v9.3.0`

2024-08-16 15:53 UTC, trusktr requested changes
Looks good, just typo and adjustment and let's merge

2024-08-16 15:53 UTC, trusktr commented
Btw what happens with latest mermaid? Is there an error or something?

2024-08-16 16:04 UTC, paulhibbitts commented on docs/markdown.md
> +!> Currently, docsify doesn't support the async mermaid render ( the limited supported latest merimaid version is `v9.3.0`).
Good eyes @trusktr 👀, thanks!

2024-08-17 00:43 UTC, sy-records commented on docs/markdown.md
> +!> Currently, docsify doesn't support the async mermaid render ( the limited supported latest merimaid version is `v9.3.0`).
```suggestion
!> Currently, docsify doesn't support the async mermaid render (the latest mermaid version supported is `v9.3.0`).
```

2024-08-17 00:45 UTC, sy-records approved these changes

2024-08-17 06:00 UTC, Koooooo-7 commented
> Btw what happens with latest mermaid? Is there an error or something?

The mermaid makes a breaking change that it only support the async render after > v9.3, but we use the `marked` in synchronization. Hence user can not simply replace the code render with async functions, it gonna get a wrong `Promised`.

2024-08-17 17:43 UTC, paulhibbitts approved these changes
LGTM, thank you!

2024-08-18 12:18 UTC, merged