[Snyk] Upgrade dexie from 4.0.8 to 4.0.9
docsifyjs/docsify pull request #2515
Opened 2024-11-16 04:05 UTC by anikethsaha

![snyk-top-banner](https://redirect.github.com/andygongea/OWASP-Benchmark/assets/818805/c518c423-16fe-447e-b67f-ad5a49b5d123)

<h3>Snyk has created this PR to upgrade dexie from 4.0.8 to 4.0.9.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.

<hr/>

- The recommended version is **2 versions** ahead of your current version.

- The recommended version was released on **a month ago**.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>dexie</b></summary>
    <ul>
      <li>
        <b>4.0.9</b> - <a href="https://redirect.github.com/dexie/Dexie.js/releases/tag/v4.0.9">2024-10-21</a></br><h1>Bugfixes</h1>
<p><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2352654316" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2011" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2011/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2011">#2011</a>: Dexie returns duplicated object after manually deleting the database and re-populate it<br>
<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2500833559" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2064" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2064/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2064">#2064</a> Failed to execute 'cmp' on 'IDBFactory': The parameter is not a valid key.<br>
<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2540076652" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2073" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2073/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2073">#2073</a> Uses cmp for sortBy<br>
<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2556683769" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2078" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2078/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2078">#2078</a> DexiePromise does not have withResolvers<br>
<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2511134052" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2067" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2067/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2067">#2067</a> useLiveQuery does not update when multiple items are deleted</p>
<p><em>Note: The Y.js support is released in 4.1.0 in alpha and possible to test but there is still no official release published for it. Also, the API might change from how it is right now. Will need some more testing and documentation before publishing it with release notes</em></p>
      </li>
      <li>
        <b>4.0.9-alpha.1</b> - 2024-08-23
      </li>
      <li>
        <b>4.0.8</b> - <a href="https://redirect.github.com/dexie/Dexie.js/releases/tag/v4.0.8">2024-07-10</a></br><p>Here's a maintainance release with small things so far.</p>
<p><em>NOTE: We're also working to release a 4.1 later this summer with CRDT support for rich text editing by providing explicit support for Y.js documents into both Dexie.js and Dexie Cloud (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2197645602" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/1926" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/1926/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/1926">#1926</a>)</em></p>
<h2>Solved issues</h2>
<ul>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2318348732" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2001" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2001/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2001">#2001</a> Typings: circular reference on update</li>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2329237445" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2004" data-hovercard-type="pull_request" data-hovercard-url="/dexie/Dexie.js/pull/2004/hovercard" href="https://redirect.github.com/dexie/Dexie.js/pull/2004">#2004</a> Add complete ./dist/* to package.json exports</li>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2382951861" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2026" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2026/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2026">#2026</a> Typings error with Table.update()</li>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2352654316" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2011" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2011/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2011">#2011</a> and <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2357369292" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2012" data-hovercard-type="issue" data-hovercard-url="/dexie/Dexie.js/issues/2012/hovercard" href="https://redirect.github.com/dexie/Dexie.js/issues/2012">#2012</a>: bulkPut() of multiple objects with same primary key would result i liveQueries showing multiple results instead of the last entry only (which is the correct result).</li>
</ul>
<h2>PRs:</h2>
<ul>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2334259316" data-permission-text="Title is private" data-url="https://github.com/dexie/Dexie.js/issues/2006" data-hovercard-type="pull_request" data-hovercard-url="/dexie/Dexie.js/pull/2006/hovercard" href="https://redirect.github.com/dexie/Dexie.js/pull/2006">#2006</a> requireAuth with options. Now possible to provide requireAuth: {email, otp, otpId} instead of just requireAuth: true. Useful when implementing magic link authentication.</li>
</ul>
<h2>dexie-cloud-addon@4.0.8:</h2>
<ul>
<li>Fix the 10-seconds pause issue: <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/dexie/Dexie.js/commit/fdd9844dc1bb4b81876ed6f144134f34ccc950fb/hovercard" href="https://redirect.github.com/dexie/Dexie.js/commit/fdd9844dc1bb4b81876ed6f144134f34ccc950fb"><tt>fdd9844</tt></a></li>
</ul>
      </li>
    </ul>
    from <a href="https://redirect.github.com/dexie/Dexie.js/releases">dexie GitHub release notes</a>
  </details>
</details>

---

> [!IMPORTANT]
>
> - Check the changes in this PR to ensure they won't cause issues with your project.
> - This PR was automatically created by Snyk using the credentials of a real user.

---

**Note:** _You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs._

**For more information:** <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiIyNzU3MzQ2MS1iMzY3LTRmMWQtOWIzYy03ZWQ5ZDQwMTAyYTgiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6IjI3NTczNDYxLWIzNjctNGYxZC05YjNjLTdlZDlkNDAxMDJhOCJ9fQ==" width="0" height="0"/>

> - 🧐 [View latest project report](https://app.snyk.io/org/anikethsaha/project/836f877b-b98e-47ed-89fc-554e9b2e146d?utm_s [...]

2024-11-18 15:47 UTC, Koooooo-7 requested changes
search broken on the preview.

2024-11-19 08:22 UTC, sy-records commented
@Koooooo-7 I tested the search in the preview fine, is that where you found it?

<img width="683" alt="image" src="https://github.com/user-attachments/assets/29029171-6985-4991-a09c-60e10cbf87d8">

2024-11-19 09:01 UTC, Koooooo-7 commented
-- @sy-records  it works fine now...I doubt something wrong on my side.
I remembered it showed some element not find issue on console and the search not work yesterday.

2024-11-19 09:01 UTC, Koooooo-7 approved these changes

2024-11-19 09:03 UTC, sy-records approved these changes

2024-11-19 09:04 UTC, merged